version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT:-development}
    image: tootiredone/app
    depends_on:
      - redis
    environment:
      REDIS_URL: 'redis://redis:6379/0'
    volumes:
      - '.:/opt/app'
    ports:
      - "8000:8000"

  rq-worker:
    image: tootiredone/app
    depends_on:
      - app
    command: rq worker -u redis://redis:6379/0
    deploy:
      replicas: 2

  redis:
    image: 'redis:6'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
